"""empty message

Revision ID: 159322f619ad
Revises: 0fb2e4286158
Create Date: 2023-02-15 12:40:44.783252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159322f619ad'
down_revision = '0fb2e4286158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_users')
    # ### end Alembic commands ###
